bootstrap.servers=kafka:9092
group.id=kafka-jev-connect-worker
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
config.storage.topic=_connect-configs
offset.storage.topic=_connect-offsets
status.storage.topic=_connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
offset.flush.interval.ms=1000
plugin.path=/opt/kafka/plugins
listeners=http://0.0.0.0:8083
rest.advertised.host.name=connect
